name: Continuous build - conda

on:
  schedule:
    - cron: "1 1 1 */1 *"
  push:
    branches: [ main, dev, pg* ]
  pull_request:
    branches: [ main, dev, pg* ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.9"]
    steps:
    - uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: conda-forge
    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.email "github_ci@test.test"
        git config --global user.name "github ci"

    - name: Install datalad & h5py with ROS3 driver
      run: conda install -c conda-forge datalad h5py

    - name: Cloning NWBE repo
      run: |
        git clone --branch development https://github.com/MetaCell/nwb-explorer

    - name: Install additional Python dependencies
      run: |
        pip install wheel
        pip install --requirement requirements.txt --quiet
        pip install --editable nwb-explorer

    - name: Install NWBE locally
      run: python nwb-explorer/utilities/install.py

    - name: Tests
      run: |
        echo Testing scripts...
        python nwb_table_readme.py --dandiset_limit
        python nwb_table_readme.py --update_readme_only 
        python nwbinspector_bulk.py

    - name: Final file info
      run: |
        ls -alt
        ls -alt validation_folder
        df -h
        du -h

    - name: Final version info
      run: |
        pip list
