
name: Continuous build

on:
  schedule:
    - cron: "1 1 1 */1 *"
  push:
    branches: [ main, dev, pg_tests ]
  pull_request:
    branches: [ main, dev, pg_tests ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, "3.10" ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
        
    - name: Test scripts
      run: |
       echo Testing scripts...
        
    - name: Final version info
      run: |
        pip list
